### ISSUE TITLE
Adding support for custom macros

### ISSUE THREAD

**Issue by DamienCassou** [jlhg/texinfo2epub#3]
Hi,

I've recently converted many texinfo manuals to epub and have been enjoying reading technical documentation on my ereader ever since. You project has made my life much more enjoyable, thank you.

I found one epub though were pieces of texts were missing, e.g.,:

```texinfo
However, the same shortcut, issued when the REPL is alive,
will bring you back to the buffer you came from, as explained in
@altr{switching-repl-buff,this section,The source and the REPL,.}
```

This is an excerpt from [the geiser's manual](https://gitlab.com/jaor/geiser/-/blob/0.11/doc/repl.texi#L140).

`altr` is [defined as follow](https://gitlab.com/jaor/geiser/-/blob/0.11/doc/macros.texi#L41):

```texinfo
@macro altr{LINK, TXT, TLINK, TRAIL}
@ifhtml
@ref{\LINK\,,\TXT\}\TRAIL\
@end ifhtml
@ifinfo
@pxref{\LINK\,\TXT\}\TRAIL\
@end ifinfo
@iftex
@ref{\TLINK\}\TRAIL\
@end iftex
@end macro
```

Is there a way to get some support for that kind of macros?

Thank you again for this wonderful project. I will convert more info manuals.

**Comment by jlhg** [comment]
In your example, the entrypoint file is geiser.text and it has included macros (https://gitlab.com/jaor/geiser/-/blob/0.11/doc/geiser.texi#L7).

The following command should work fine:

```
./texinfo2epub.sh geiser/doc/geiser.texi geiser.epub
```

If the output EPUB file can't open, you can import it into Calibre and convert to EPUB again.

**Comment by DamienCassou** [comment]
Here is a screenshot of E-book viewer. The end of the first paragraph is missing:

![2020-02-17-164114](https://user-images.githubusercontent.com/217543/74667854-5887c280-51a4-11ea-88e9-c95ef21cadbb.png)

**Comment by cldotdev** [comment]
@DamienCassou 

You should add the following to macros.texi (https://gitlab.com/jaor/geiser/-/blob/master/doc/macros.texi#L50)

```
@ifdocbook
@ref{\TLINK\}\TRAIL\
@end ifdocbook
```

**Comment by cldotdev** [comment]
The result will look like:

<img width="1022" alt="截圖 2020-02-17 23 44 46" src="https://user-images.githubusercontent.com/2265716/74668146-90602b80-51df-11ea-9f45-a77f359a6e9c.png">

**Comment by DamienCassou** [comment]
This works great, thank you. Do you know what I could add for the other 2 macros?

```texi
@macro img{FILE, ALIGN}
@ifhtml
@html
<img src="img/\FILE\.png" class="float\ALIGN\"/>
@end html
@end ifhtml
@end macro

@macro imgc{FILE}
@ifhtml
@html
<img src="img/\FILE\.png"/>
@end html
@end ifhtml
@end macro
```

**Comment by cldotdev** [comment]
You can use the following macro:

```texi
@macro img{FILE, ALIGN}
@ifhtml
@html
<img src="img/\FILE\.png" class="float\ALIGN\"/>
@end html
@end ifhtml
@ifdocbook
@image{img/\FILE\,,,,.png}
@end ifdocbook
@end macro

@macro imgc{FILE}
@ifhtml
@html
<img src="img/\FILE\.png"/>
@end html
@end ifhtml
@ifdocbook
@image{img/\FILE\,,,,.png}
@end ifdocbook
@end macro
```

and add `cp -r $(dirname $INPUT_FILE_PATH)/img OEBPS` to texinfo2epub.sh#L43

**Comment by DamienCassou** [comment]
Thank you very much. It works. I created https://github.com/jlhg/texinfo2epub/issues/4 to discuss if modifying texinfo2epub can be done in a reusable way.
