### ISSUE TITLE
Add resources to the epub

### ISSUE THREAD

**Issue by DamienCassou** [jlhg/texinfo2epub#4]
Hi,

my texi file references some co-located pictures. Would it be possible to improve texinfo2epub so the generated epub contains the pictures too?

See https://github.com/jlhg/texinfo2epub/issues/3 for details.

**Comment by cldotdev** [comment]
@DamienCassou I've added a python script to copy image files to the EPUB.

**Comment by DamienCassou** [comment]
Thank you. This works fine when https://github.com/jlhg/texinfo2epub/pull/5 is merged.
