### ISSUE TITLE
linefeed in mimetype

### ISSUE THREAD

**Issue by m-elagin** [jlhg/texinfo2epub#6]
When validating a epub produced by texinfo2pub, epubcheck 4.2.4 complains:

ERROR(PKG-007): R-lang.epub/mimetype(-1,-1): Mimetype file should only contain the string "application/epub+zip" and should not be compressed.

This is due to a trailing linefeed put into mimetype by "echo". Adding "-n" to "echo" fixes the issue.

**Comment by cldotdev** [comment]
Already fixed by commit e6b0129055eebdbfccaf7433ef0eec82b0c374fb.
